name: Deploy to Fly

on:
  push:
    branches: [main]
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: |
          # 注入敏感 Secrets 到环境变量
          flyctl secrets set POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          
          # 构建 DSN（使用 Secrets，避免泄露）
          export MEMOS_DSN="postgresql://postgres:${POSTGRES_PASSWORD}@db.mxthmqnzpuzfrneiucnj.supabase.co:5432/postgres"
          flyctl secrets set MEMOS_DSN="$MEMOS_DSN"
          
          # 部署（使用 fly.toml 配置）
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
